import 'package:flutter/material.dart' show Color, MaterialColor;

class YaruColors {
  YaruColors._();

  static const int _ubuntuOrangePrimaryValue = 0xFFE95420;

  static const MaterialColor ubuntuOrange =
      MaterialColor(_ubuntuOrangePrimaryValue, {
    50: Color(0xFFFDEEE9),
    100: Color(0xFFFBDDD2),
    200: Color(0xFFF6BBA6),
    300: Color(0xFFF29879),
    400: Color(0xFFED764D),
    500: Color(_ubuntuOrangePrimaryValue),
    600: Color(0xFFBA431A),
    700: Color(0xFF8C3213),
    800: Color(0xFF5D220D),
    900: Color(0xFF2F1106),
  });

  static const int _warmGreyPrimaryValue = 0xFFAEA79F;

  static const MaterialColor warmGrey = MaterialColor(_warmGreyPrimaryValue, {
    50: Color(0xFFF6F6F5),
    100: Color(0xFFEEEDEB),
    200: Color(0xFFDEDBD8),
    300: Color(0xFFCECAC5),
    400: Color(0xFFBEB8B2),
    500: Color(_warmGreyPrimaryValue),
  });

  static const Color coolGrey = Color(0xFF333333);
  static const Color textGrey = Color(0xFF111111);
  static const Color red = Color(0xFFff0000);
  static const Color yellow = Color(0xFFf99b11);
  static const Color green = Color(0xFF0e8420);
  static const Color disabledGreyDark = Color(0xFF535353);
  static const Color porcelain = Color(0xFFFAFAFA);
  static const Color inkstone = Color(0xFF3B3B3B);
  static const Color jet = Color(0xFF2B2B2B);

  // Generated by tool/colorgen.dart
  static const olive = MaterialColor(0xFF4B8501, {
    50: Color(0xFF9CBC73),
    100: Color(0xFF93B667),
    200: Color(0xFF81AA4D),
    300: Color(0xFF6F9D34),
    400: Color(0xFF5D911A),
    500: Color(0xFF4B8501),
    600: Color(0xFF437801),
    700: Color(0xFF3C6A01),
    800: Color(0xFF345D01),
    900: Color(0xFF2D5001)
  });

  // Generated by tool/colorgen.dart
  static const bark = MaterialColor(0xFF787859, {
    50: Color(0xFFB5B5A4),
    100: Color(0xFFAEAE9B),
    200: Color(0xFFA1A18B),
    300: Color(0xFF93937A),
    400: Color(0xFF86866A),
    500: Color(0xFF787859),
    600: Color(0xFF6C6C50),
    700: Color(0xFF606047),
    800: Color(0xFF54543E),
    900: Color(0xFF484835)
  });

  // Generated by tool/colorgen.dart
  static const sage = MaterialColor(0xFF657B69, {
    50: Color(0xFFAAB6AD),
    100: Color(0xFFA3B0A5),
    200: Color(0xFF93A396),
    300: Color(0xFF849587),
    400: Color(0xFF748878),
    500: Color(0xFF657B69),
    600: Color(0xFF5B6F5E),
    700: Color(0xFF516254),
    800: Color(0xFF475649),
    900: Color(0xFF3D4A3F)
  });

  // Generated by tool/colorgen.dart
  static const prussianGreen = MaterialColor(0xFF308280, {
    50: Color(0xFF8DBAB9),
    100: Color(0xFF83B4B3),
    200: Color(0xFF6EA8A6),
    300: Color(0xFF599B99),
    400: Color(0xFF458F8D),
    500: Color(0xFF308280),
    600: Color(0xFF2B7573),
    700: Color(0xFF266866),
    800: Color(0xFF225B5A),
    900: Color(0xFF1D4E4D)
  });

  // Generated by tool/colorgen.dart
  static const viridian = MaterialColor(0xFF03875B, {
    50: Color(0xFF74BDA5),
    100: Color(0xFF68B79D),
    200: Color(0xFF4FAB8C),
    300: Color(0xFF359F7C),
    400: Color(0xFF1C936B),
    500: Color(0xFF03875B),
    600: Color(0xFF037952),
    700: Color(0xFF026C49),
    800: Color(0xFF025E40),
    900: Color(0xFF025137)
  });

  // Generated by tool/colorgen.dart
  static const purple = MaterialColor(0xFF8856EB, {
    50: Color(0xFFBEA2F4),
    100: Color(0xFFB89AF3),
    200: Color(0xFFAC89F1),
    300: Color(0xFFA078EF),
    400: Color(0xFF9467ED),
    500: Color(0xFF8856EB),
    600: Color(0xFF7A4DD3),
    700: Color(0xFF6D45BC),
    800: Color(0xFF5F3CA4),
    900: Color(0xFF52348D)
  });

  // Generated by tool/colorgen.dart
  static const lightRed = MaterialColor(0xFFE61D34, {
    50: Color(0xFFF1838F),
    100: Color(0xFFF07785),
    200: Color(0xFFEE6171),
    300: Color(0xFFEB4A5D),
    400: Color(0xFFE93448),
    500: Color(0xFFE61D34),
    600: Color(0xFFCF1A2F),
    700: Color(0xFFB8172A),
    800: Color(0xFFA11424),
    900: Color(0xFF8A111F)
  });

  // Generated by tool/colorgen.dart
  static const blue = MaterialColor(0xFF0073E5, {
    50: Color(0xFF73B2F1),
    100: Color(0xFF66ABEF),
    200: Color(0xFF4D9DED),
    300: Color(0xFF338FEA),
    400: Color(0xFF1A81E8),
    500: Color(0xFF0073E5),
    600: Color(0xFF0067CE),
    700: Color(0xFF005CB7),
    800: Color(0xFF0050A0),
    900: Color(0xFF004589)
  });

  // Generated by tool/colorgen.dart
  static const magenta = MaterialColor(0xFFBC33DB, {
    50: Color(0xFFDA8FEB),
    100: Color(0xFFD785E9),
    200: Color(0xFFD070E6),
    300: Color(0xFFC95CE2),
    400: Color(0xFFC347DF),
    500: Color(0xFFBC33DB),
    600: Color(0xFFA92EC5),
    700: Color(0xFF9629AF),
    800: Color(0xFF842499),
    900: Color(0xFF711F83)
  });
}
