import 'package:flutter/material.dart' show Color, MaterialColor;

class YaruColors {
  YaruColors._();

  static const _ubuntuOrangePrimaryValue = 0xFFE95622;
  static const ubuntuOrange = MaterialColor(_ubuntuOrangePrimaryValue, {
    50: Color(0xFFF9E9E7),
    100: Color(0xFFFBCCBD),
    200: Color(0xFFF9AC92),
    300: Color(0xFFF68C67),
    400: Color(0xFFF57445),
    500: Color(0xFFF45D26),
    600: Color(_ubuntuOrangePrimaryValue),
    700: Color(0xFFDB501E),
    800: Color(0xFFCD4A1A),
    900: Color(0xFFB43E14),
  });

  static const int _warmGreyPrimaryValue = 0xFFAEA79F;

  static const MaterialColor warmGrey = MaterialColor(_warmGreyPrimaryValue, {
    50: Color(0xFFF6F6F5),
    100: Color(0xFFEEEDEB),
    200: Color(0xFFDEDBD8),
    300: Color(0xFFCECAC5),
    400: Color(0xFFBEB8B2),
    500: Color(_warmGreyPrimaryValue),
  });

  static const Color coolGrey = Color(0xFF333333);
  static const Color textGrey = Color(0xFF111111);
  static const Color red = Color(0xFFff0000);
  static const Color yellow = Color(0xFFf99b11);
  static const Color green = Color(0xFF0e8420);
  static const Color disabledGreyDark = Color(0xFF535353);
  static const Color porcelain = Color(0xFFFAFAFA);
  static const Color inkstone = Color(0xFF3B3B3B);
  static const Color jet = Color(0xFF2B2B2B);

  static const _olivePrimaryValue = 0xFF4B8501;
  static const olive = MaterialColor(_olivePrimaryValue, {
    50: Color(0xFFF1F7E6),
    100: Color(0xFFDBEAC0),
    200: Color(0xFFC3DD97),
    300: Color(0xFFABCF6C),
    400: Color(0xFF98C54A),
    500: Color(0xFF85BC22),
    600: Color(0xFF76AC1A),
    700: Color(0xFF61990E),
    800: Color(_olivePrimaryValue),
    900: Color(0xFF236400),
  });

  static const _barkPrimaryValue = 0xFF787859;
  static const bark = MaterialColor(_barkPrimaryValue, {
    50: Color(0xFFFDFCD9),
    100: Color(0xFFF7F7D3),
    200: Color(0xFFF2F1CE),
    300: Color(0xFFE4E3C0),
    400: Color(0xFFC1C09E),
    500: Color(0xFFA2A181),
    600: Color(_barkPrimaryValue),
    700: Color(0xFF646446),
    800: Color(0xFF444528),
    900: Color(0xFF232305),
  });

  static const _sagePrimaryValue = 0xFF657B69;
  static const sage = MaterialColor(_sagePrimaryValue, {
    50: Color(0xFFE8FFEC),
    100: Color(0xFFE2FBE6),
    200: Color(0xFFDCF5E0),
    300: Color(0xFFCEE7D2),
    400: Color(0xFFACC4B0),
    500: Color(0xFF8DA491),
    600: Color(_sagePrimaryValue),
    700: Color(0xFF516755),
    800: Color(0xFF334737),
    900: Color(0xFF132617),
  });

  // Generated by tool/colorgen.dart
  static const _prussianGreenPrimaryValue = 0xFF308280;
  static const prussianGreen = MaterialColor(_prussianGreenPrimaryValue, {
    50: Color(0xFFE1F7F6),
    100: Color(0xFFB6EBE8),
    200: Color(0xFF89DEDC),
    300: Color(0xFF60D0CF),
    400: Color(0xFF49C6C7),
    500: Color(0xFF3BBCC1),
    600: Color(0xFF38ACAF),
    700: Color(0xFF349697),
    800: Color(_prussianGreenPrimaryValue),
    900: Color(0xFF285E59),
  });

  // Generated by tool/colorgen.dart
  static const _viridianPrimaryValue = 0xFF03875B;
  static const viridian = MaterialColor(_viridianPrimaryValue, {
    50: Color(0xFFE6F7EF),
    100: Color(0xFFC3EAD8),
    200: Color(0xFF9BDDC0),
    300: Color(0xFF70D0A7),
    400: Color(0xFF4BC694),
    500: Color(0xFF15BB81),
    600: Color(0xFF0DAB76),
    700: Color(0xFF049968),
    800: Color(_viridianPrimaryValue),
    900: Color(0xFF046744),
  });

  static const _purplePrimaryValue = 0xFF8856EB;
  static const purple = MaterialColor(_purplePrimaryValue, {
    50: Color(0xFFF0E8FC),
    100: Color(0xFFD6C6F7),
    200: Color(0xFFBB9FF3),
    300: Color(0xFF9F76EF),
    400: Color(_purplePrimaryValue),
    500: Color(0xFF6F35E6),
    600: Color(0xFF6330DF),
    700: Color(0xFF5327D7),
    800: Color(0xFF4120D0),
    900: Color(0xFF2113C2),
  });

  static const _lightRedPrimaryValue = 0xFFE61D34;
  static const lightRed = MaterialColor(_lightRedPrimaryValue, {
    50: Color(0xFFFFEAEE),
    100: Color(0xFFFFCAD2),
    200: Color(0xFFEF9499),
    300: Color(0xFFE56A72),
    400: Color(0xFFF04350),
    500: Color(0xFFF52935),
    600: Color(_lightRedPrimaryValue),
    700: Color(0xFFD40D2E),
    800: Color(0xFFC70027),
    900: Color(0xFFB9001A),
  });

  static const _bluePrimaryValue = 0xFF0073E5;
  static const blue = MaterialColor(_bluePrimaryValue, {
    50: Color(0xFFE2F2FF),
    100: Color(0xFFB9DEFF),
    200: Color(0xFF8BC9FF),
    300: Color(0xFF59B4FF),
    400: Color(0xFF2BA3FF),
    500: Color(0xFF0093FF),
    600: Color(0xFF0085F9),
    700: Color(_bluePrimaryValue),
    800: Color(0xFF0861D3),
    900: Color(0xFF1041B4),
  });

  static const _magentaPrimaryValue = 0xFFBC33DB;
  static const magenta = MaterialColor(_magentaPrimaryValue, {
    50: Color(0xFFF6E5FA),
    100: Color(0xFFE8BDF2),
    200: Color(0xFFD98FEA),
    300: Color(0xFFC95FE2),
    400: Color(_magentaPrimaryValue),
    500: Color(0xFFAF00D4),
    600: Color(0xFF9E00CE),
    700: Color(0xFF8700C8),
    800: Color(0xFF7300C2),
    900: Color(0xFF4700B6),
  });
}
