name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  FLUTTER_VERSION: 3.13.x

jobs:
  analyze:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{env.FLUTTER_VERSION}}

    - name: Get dependencies
      run: flutter pub get

    - name: Check for any analyzer issues
      run: flutter analyze .

  build:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{env.FLUTTER_VERSION}}

    - name: Get dependencies
      run: flutter pub get

    - name: Install dependencies
      run: sudo apt install clang cmake curl ninja-build libgtk-3-dev pkg-config unzip

    - name: Build example
      run: flutter build linux -v
      working-directory: example/

  format:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{env.FLUTTER_VERSION}}

    - name: Check for any formatting issues
      run: dart format --set-exit-if-changed .

  pub:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{env.FLUTTER_VERSION}}

    - name: Get dependencies
      run: flutter pub get

    - name: Validate but do not publish the package
      run: flutter pub publish --dry-run

  test:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{env.FLUTTER_VERSION}}

    - name: Get dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test
