name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  analyze:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.10.x'

    - name: Get dependencies
      run: flutter pub get

    - name: Check for any analyzer issues
      run: flutter analyze .

  build:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.10.x'

    - name: Get dependencies
      run: flutter pub get

    - name: Install dependencies
      run: sudo apt install clang cmake curl ninja-build libgtk-3-dev pkg-config unzip

    - name: Build example
      run: flutter build linux -v
      working-directory: example/

  format:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.10.x'

    - name: Check for any formatting issues
      run: dart format --set-exit-if-changed .

  goldens:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.10.x'

    - name: Install apt dependencies
      run: |
        sudo apt update
        sudo apt -y install clang cmake curl libgtk-3-dev ninja-build pkg-config unzip xvfb
        sudo apt -y install fonts-noto-cjk fonts-ubuntu fonts-tibetan-machine

    - name: Get pub dependencies
      run: flutter pub get

    - name: Run golden tests
      run: xvfb-run -a -s '-screen 0 1280x800x24 +extension GLX' flutter test integration_test/golden_test.dart -d linux
      working-directory: example/

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: failures
        path: example/integration_test/failures

  pub:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.10.x'

    - name: Get dependencies
      run: flutter pub get

    - name: Validate but do not publish the package
      run: flutter pub publish --dry-run

  test:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.10.x'

    - name: Get dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test
