name: Publish to GitHub Pages

on:
  push:
    branches: [main]

env:
  FLUTTER_VERSION: 3.10.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: example
          baseHref: /yaru.dart/
          webRenderer: canvaskit
